import { QuoteEntry } from './types';

export const MOCK_QUOTE_DATA: QuoteEntry[] = [
    {
        id: 1,
        city: '山东省枣庄市滕州市',
        serviceItem: '名酒回收',
        serviceTime: '0-23',
        priceType: '日常价格',
        companyQuote: '',
        settlementPrice: '',
        jumpPrice: '',
        splitRatio: '',
        content: '机器人录单自动匹配详情的价格信息30一次',
        hasImage: false,
        remark: ''
    },
    {
        id: 2,
        city: '湖北省孝感市应城市',
        serviceItem: '手机回收',
        serviceTime: '0-23',
        priceType: '日常价格',
        companyQuote: '',
        settlementPrice: '',
        jumpPrice: '',
        splitRatio: '',
        content: '普通安卓手机回收一个30；iOS手机回收一个50；品相好的酌情提高回收金额',
        hasImage: false,
        remark: ''
    },
    {
        id: 3,
        city: '北京市东城区',
        serviceItem: '甲醛检测',
        serviceTime: '0-20',
        priceType: '日常价格',
        companyQuote: '0.04',
        settlementPrice: '0.04',
        jumpPrice: '0.04',
        splitRatio: '0.04',
        content: '每个点位100，按平方数计算',
        hasImage: true,
        remark: '是啥事'
    },
    {
        id: 4,
        city: '北京市西城区',
        serviceItem: '焊接服务',
        serviceTime: '0-1',
        priceType: '日常价格',
        companyQuote: '2.00',
        settlementPrice: '3.00',
        jumpPrice: '108.00',
        splitRatio: '0.20',
        content: '根据焊接类型沟通报价',
        hasImage: false,
        remark: ''
    },
    {
        id: 5,
        city: '四川省自贡市贡井区',
        serviceItem: '家电回收',
        serviceTime: '18-22',
        priceType: '节假日价格',
        companyQuote: '12.00',
        settlementPrice: '32.00',
        jumpPrice: '60.00',
        splitRatio: '0.40',
        content: '挂机：定频空调80元一个压力，变频90元一个压力，缺多少个压力补多少个压力。柜机：100元一个压力，缺多少个压力补多中央空调：120元一个压力',
        hasImage: false,
        remark: ''
    },
    {
        id: 6,
        city: '四川省自贡市贡井区',
        serviceItem: '家电回收',
        serviceTime: '18-22',
        priceType: '节假日价格',
        companyQuote: '18.00',
        settlementPrice: '33.00',
        jumpPrice: '85.00',
        splitRatio: '0.30',
        content: '挂机：定频空调80元一个压力，变频90元一个压力，缺多少个压力补多少个压力。柜机：100元一个压力，缺多少个压力补多中央空调：120元一个压力',
        hasImage: false,
        remark: ''
    },
    {
        id: 7,
        city: '四川省自贡市贡井区',
        serviceItem: '家电回收',
        serviceTime: '18-22',
        priceType: '节假日价格',
        companyQuote: '15.00',
        settlementPrice: '35.00',
        jumpPrice: '65.00',
        splitRatio: '0.30',
        content: '挂机：定频空调80元一个压力，变频90元一个压力，缺多少个压力补多少个压力。柜机：100元一个压力，缺多少个压力补多中央空调：120元一个压力',
        hasImage: false,
        remark: ''
    },
    {
        id: 8,
        city: '四川省自贡市贡井区',
        serviceItem: '家电回收',
        serviceTime: '18-22',
        priceType: '节假日价格',
        companyQuote: '17.00',
        settlementPrice: '37.00',
        jumpPrice: '67.00',
        splitRatio: '0.30',
        content: '挂机：定频空调80元一个压力，变频90元一个压力，缺多少个压力补多少个压力。柜机：100元一个压力，缺多少个压力补多中央空调：120元一个压力',
        hasImage: false,
        remark: ''
    },
    {
        id: 9,
        city: '四川省自贡市贡井区',
        serviceItem: '家电回收',
        serviceTime: '18-22',
        priceType: '节假日价格',
        companyQuote: '19.00',
        settlementPrice: '39.00',
        jumpPrice: '69.00',
        splitRatio: '0.30',
        content: '挂机：定频空调80元一个压力，变频90元一个压力，缺多少个压力补多少个压力。柜机：100元一个压力，缺多少个压力补多中央空调：120元一个压力',
        hasImage: false,
        remark: ''
    },
    {
        id: 10,
        city: '四川省自贡市贡井区',
        serviceItem: '家电回收',
        serviceTime: '18-22',
        priceType: '节假日价格',
        companyQuote: '21.00',
        settlementPrice: '41.00',
        jumpPrice: '71.00',
        splitRatio: '0.30',
        content: '挂机：定频空调80元一个压力，变频90元一个压力，缺多少个压力补多少个压力。柜机：100元一个压力，缺多少个压力补多中央空调：120元一个压力',
        hasImage: false,
        remark: ''
    }
];